### ISSUE TITLE
ID-2129: Support contextual image names

### ISSUE THREAD

**Issue by kons-jaf** [felleslosninger/eid-github-workflows#53]
We have image names that include a "namespace", like `event-statistikk/stat-ingester` and `event-statistikk/brukeradmin-backend`.
The image name contains a slash that is interpreted as a directory-separator in the `anchore/sbom`-action when specified as the `artifact-name`: https://github.com/felleslosninger/brukeradmin-backend/actions/runs/3297077884/jobs/5437472307#step:11:198

**Comment by oyri** [comment]
I see, but maybe we then need an input param for name or filter out slashes, preferably the last since my long term hope is to publish this to a SBOM server so we easily can search for applications containing a given dependacy/vunerability. Then we need to include the name of the application or repo in the name as well. E.g. replace slash with underscore or something would then be good.

**Comment by kons-jaf** [comment]
https://digdir.atlassian.net/browse/ID-2149 created.
